# Generated by Django 3.0.8 on 2020-11-06 19:10

import MSV.models.customer
import MSV.models.shop
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to=MSV.models.shop.name_image)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Account')),
                ('address', models.ManyToManyField(to='MSV.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to=MSV.models.customer.name_image)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Account')),
                ('address', models.ManyToManyField(to='MSV.Address')),
            ],
        ),
    ]
