# Generated by Django 3.0.8 on 2020-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSV', '0002_address_customer_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='follower',
            field=models.ManyToManyField(related_name='shop_followed', to='MSV.Customer'),
        ),
    ]
