# Generated by Django 3.0.8 on 2020-11-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSV', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_date', models.DateField(auto_now=True)),
                ('shipped_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOrdered', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSV.Product')),
            ],
        ),
    ]
